[package]
name = "lis3dsh"
version = "0.1.0"
authors = ["Joseph Angelo <b.j.angelo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "0.2"
